# This playbook stop all apps on particular hosts
#requires --extra-vars="target=somehost"
---
- name: Stop Apps
  hosts: "{{ target }}"
  gather_facts: no
  sudo: yes
  tasks:
    - name: stop forked apps
      command: service {{ item }} stop
      when: apps_stop_only is defined
      with_items: 
        - "{{ apps_stop_only }}"
      ignore_errors: yes
    - name: stop apps
      command: service {{ item }} stop
      with_items: 
        - "{{ apps }}"
      ignore_errors: yes
